// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRPC.proto

package com.rome.common.rpc.message;

public final class MessageRPC {
  private MessageRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rome_common_rpc_message_VerificationCodeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rome_common_rpc_message_VerificationCodeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rome_common_rpc_message_VerificationCodeRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rome_common_rpc_message_VerificationCodeRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MessageRPC.proto\022\033com.rome.common.rpc." +
      "message\"S\n\023VerificationCodeReq\022\023\n\013messag" +
      "eType\030\001 \001(\t\022\017\n\007useType\030\002 \001(\t\022\026\n\016messageC" +
      "ontent\030\003 \001(\t\")\n\023VerificationCodeRes\022\022\n\nr" +
      "esultJson\030\001 \001(\t2\224\001\n\027VerificationCodeServ" +
      "ice\022y\n\023getVerificationCode\0220.com.rome.co" +
      "mmon.rpc.message.VerificationCodeReq\0320.c" +
      "om.rome.common.rpc.message.VerificationC" +
      "odeResB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_rome_common_rpc_message_VerificationCodeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rome_common_rpc_message_VerificationCodeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rome_common_rpc_message_VerificationCodeReq_descriptor,
        new java.lang.String[] { "MessageType", "UseType", "MessageContent", });
    internal_static_com_rome_common_rpc_message_VerificationCodeRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_rome_common_rpc_message_VerificationCodeRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rome_common_rpc_message_VerificationCodeRes_descriptor,
        new java.lang.String[] { "ResultJson", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
