// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRPC.proto

package com.rome.common.rpc.message;

public interface VerificationCodeResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rome.common.rpc.message.VerificationCodeRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resultJson = 1;</code>
   */
  java.lang.String getResultJson();
  /**
   * <code>string resultJson = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultJsonBytes();
}
