// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Basic.proto

package com.rome.common.rpc.basic;

public interface FileUploadResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rome.common.rpc.basic.FileUploadRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resultJson = 1;</code>
   */
  java.lang.String getResultJson();
  /**
   * <code>string resultJson = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultJsonBytes();
}
