// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Basic.proto

package com.rome.common.rpc.basic;

public interface FileUploadReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rome.common.rpc.basic.FileUploadReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string imageByte = 1;</code>
   */
  java.lang.String getImageByte();
  /**
   * <code>string imageByte = 1;</code>
   */
  com.google.protobuf.ByteString
      getImageByteBytes();

  /**
   * <code>string userAccount = 2;</code>
   */
  java.lang.String getUserAccount();
  /**
   * <code>string userAccount = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserAccountBytes();
}
