// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRPC.proto

package com.rome.common.rpc.message;

public interface VerificationCodeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rome.common.rpc.message.VerificationCodeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageType = 1;</code>
   */
  java.lang.String getMessageType();
  /**
   * <code>string messageType = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageTypeBytes();

  /**
   * <code>string useType = 2;</code>
   */
  java.lang.String getUseType();
  /**
   * <code>string useType = 2;</code>
   */
  com.google.protobuf.ByteString
      getUseTypeBytes();

  /**
   * <code>string messageContent = 3;</code>
   */
  java.lang.String getMessageContent();
  /**
   * <code>string messageContent = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageContentBytes();
}
