// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRPC.proto

package com.rome.common.rpc.message;

/**
 * Protobuf type {@code com.rome.common.rpc.message.VerificationCodeRes}
 */
public  final class VerificationCodeRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.rome.common.rpc.message.VerificationCodeRes)
    VerificationCodeResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerificationCodeRes.newBuilder() to construct.
  private VerificationCodeRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerificationCodeRes() {
    resultJson_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VerificationCodeRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            resultJson_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rome.common.rpc.message.VerificationCodeRes.class, com.rome.common.rpc.message.VerificationCodeRes.Builder.class);
  }

  public static final int RESULTJSON_FIELD_NUMBER = 1;
  private volatile java.lang.Object resultJson_;
  /**
   * <code>string resultJson = 1;</code>
   */
  public java.lang.String getResultJson() {
    java.lang.Object ref = resultJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultJson_ = s;
      return s;
    }
  }
  /**
   * <code>string resultJson = 1;</code>
   */
  public com.google.protobuf.ByteString
      getResultJsonBytes() {
    java.lang.Object ref = resultJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getResultJsonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resultJson_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getResultJsonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resultJson_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rome.common.rpc.message.VerificationCodeRes)) {
      return super.equals(obj);
    }
    com.rome.common.rpc.message.VerificationCodeRes other = (com.rome.common.rpc.message.VerificationCodeRes) obj;

    if (!getResultJson()
        .equals(other.getResultJson())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULTJSON_FIELD_NUMBER;
    hash = (53 * hash) + getResultJson().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rome.common.rpc.message.VerificationCodeRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rome.common.rpc.message.VerificationCodeRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.rome.common.rpc.message.VerificationCodeRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.rome.common.rpc.message.VerificationCodeRes)
      com.rome.common.rpc.message.VerificationCodeResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rome.common.rpc.message.VerificationCodeRes.class, com.rome.common.rpc.message.VerificationCodeRes.Builder.class);
    }

    // Construct using com.rome.common.rpc.message.VerificationCodeRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      resultJson_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeRes_descriptor;
    }

    @java.lang.Override
    public com.rome.common.rpc.message.VerificationCodeRes getDefaultInstanceForType() {
      return com.rome.common.rpc.message.VerificationCodeRes.getDefaultInstance();
    }

    @java.lang.Override
    public com.rome.common.rpc.message.VerificationCodeRes build() {
      com.rome.common.rpc.message.VerificationCodeRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rome.common.rpc.message.VerificationCodeRes buildPartial() {
      com.rome.common.rpc.message.VerificationCodeRes result = new com.rome.common.rpc.message.VerificationCodeRes(this);
      result.resultJson_ = resultJson_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rome.common.rpc.message.VerificationCodeRes) {
        return mergeFrom((com.rome.common.rpc.message.VerificationCodeRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rome.common.rpc.message.VerificationCodeRes other) {
      if (other == com.rome.common.rpc.message.VerificationCodeRes.getDefaultInstance()) return this;
      if (!other.getResultJson().isEmpty()) {
        resultJson_ = other.resultJson_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.rome.common.rpc.message.VerificationCodeRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.rome.common.rpc.message.VerificationCodeRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object resultJson_ = "";
    /**
     * <code>string resultJson = 1;</code>
     */
    public java.lang.String getResultJson() {
      java.lang.Object ref = resultJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resultJson = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultJsonBytes() {
      java.lang.Object ref = resultJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resultJson = 1;</code>
     */
    public Builder setResultJson(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resultJson_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string resultJson = 1;</code>
     */
    public Builder clearResultJson() {
      
      resultJson_ = getDefaultInstance().getResultJson();
      onChanged();
      return this;
    }
    /**
     * <code>string resultJson = 1;</code>
     */
    public Builder setResultJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resultJson_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.rome.common.rpc.message.VerificationCodeRes)
  }

  // @@protoc_insertion_point(class_scope:com.rome.common.rpc.message.VerificationCodeRes)
  private static final com.rome.common.rpc.message.VerificationCodeRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rome.common.rpc.message.VerificationCodeRes();
  }

  public static com.rome.common.rpc.message.VerificationCodeRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerificationCodeRes>
      PARSER = new com.google.protobuf.AbstractParser<VerificationCodeRes>() {
    @java.lang.Override
    public VerificationCodeRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VerificationCodeRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VerificationCodeRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerificationCodeRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rome.common.rpc.message.VerificationCodeRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

