// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRPC.proto

package com.rome.common.rpc.message;

/**
 * Protobuf type {@code com.rome.common.rpc.message.VerificationCodeReq}
 */
public  final class VerificationCodeReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.rome.common.rpc.message.VerificationCodeReq)
    VerificationCodeReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerificationCodeReq.newBuilder() to construct.
  private VerificationCodeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerificationCodeReq() {
    messageType_ = "";
    useType_ = "";
    messageContent_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VerificationCodeReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            messageType_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            useType_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            messageContent_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rome.common.rpc.message.VerificationCodeReq.class, com.rome.common.rpc.message.VerificationCodeReq.Builder.class);
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object messageType_;
  /**
   * <code>string messageType = 1;</code>
   */
  public java.lang.String getMessageType() {
    java.lang.Object ref = messageType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageType_ = s;
      return s;
    }
  }
  /**
   * <code>string messageType = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMessageTypeBytes() {
    java.lang.Object ref = messageType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USETYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object useType_;
  /**
   * <code>string useType = 2;</code>
   */
  public java.lang.String getUseType() {
    java.lang.Object ref = useType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      useType_ = s;
      return s;
    }
  }
  /**
   * <code>string useType = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUseTypeBytes() {
    java.lang.Object ref = useType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      useType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGECONTENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object messageContent_;
  /**
   * <code>string messageContent = 3;</code>
   */
  public java.lang.String getMessageContent() {
    java.lang.Object ref = messageContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageContent_ = s;
      return s;
    }
  }
  /**
   * <code>string messageContent = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageContentBytes() {
    java.lang.Object ref = messageContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageType_);
    }
    if (!getUseTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, useType_);
    }
    if (!getMessageContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageContent_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageType_);
    }
    if (!getUseTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, useType_);
    }
    if (!getMessageContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageContent_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rome.common.rpc.message.VerificationCodeReq)) {
      return super.equals(obj);
    }
    com.rome.common.rpc.message.VerificationCodeReq other = (com.rome.common.rpc.message.VerificationCodeReq) obj;

    if (!getMessageType()
        .equals(other.getMessageType())) return false;
    if (!getUseType()
        .equals(other.getUseType())) return false;
    if (!getMessageContent()
        .equals(other.getMessageContent())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType().hashCode();
    hash = (37 * hash) + USETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getUseType().hashCode();
    hash = (37 * hash) + MESSAGECONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getMessageContent().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rome.common.rpc.message.VerificationCodeReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rome.common.rpc.message.VerificationCodeReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.rome.common.rpc.message.VerificationCodeReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.rome.common.rpc.message.VerificationCodeReq)
      com.rome.common.rpc.message.VerificationCodeReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rome.common.rpc.message.VerificationCodeReq.class, com.rome.common.rpc.message.VerificationCodeReq.Builder.class);
    }

    // Construct using com.rome.common.rpc.message.VerificationCodeReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageType_ = "";

      useType_ = "";

      messageContent_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rome.common.rpc.message.MessageRPC.internal_static_com_rome_common_rpc_message_VerificationCodeReq_descriptor;
    }

    @java.lang.Override
    public com.rome.common.rpc.message.VerificationCodeReq getDefaultInstanceForType() {
      return com.rome.common.rpc.message.VerificationCodeReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.rome.common.rpc.message.VerificationCodeReq build() {
      com.rome.common.rpc.message.VerificationCodeReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rome.common.rpc.message.VerificationCodeReq buildPartial() {
      com.rome.common.rpc.message.VerificationCodeReq result = new com.rome.common.rpc.message.VerificationCodeReq(this);
      result.messageType_ = messageType_;
      result.useType_ = useType_;
      result.messageContent_ = messageContent_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rome.common.rpc.message.VerificationCodeReq) {
        return mergeFrom((com.rome.common.rpc.message.VerificationCodeReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rome.common.rpc.message.VerificationCodeReq other) {
      if (other == com.rome.common.rpc.message.VerificationCodeReq.getDefaultInstance()) return this;
      if (!other.getMessageType().isEmpty()) {
        messageType_ = other.messageType_;
        onChanged();
      }
      if (!other.getUseType().isEmpty()) {
        useType_ = other.useType_;
        onChanged();
      }
      if (!other.getMessageContent().isEmpty()) {
        messageContent_ = other.messageContent_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.rome.common.rpc.message.VerificationCodeReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.rome.common.rpc.message.VerificationCodeReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object messageType_ = "";
    /**
     * <code>string messageType = 1;</code>
     */
    public java.lang.String getMessageType() {
      java.lang.Object ref = messageType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string messageType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string messageType = 1;</code>
     */
    public Builder setMessageType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string messageType = 1;</code>
     */
    public Builder clearMessageType() {
      
      messageType_ = getDefaultInstance().getMessageType();
      onChanged();
      return this;
    }
    /**
     * <code>string messageType = 1;</code>
     */
    public Builder setMessageTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object useType_ = "";
    /**
     * <code>string useType = 2;</code>
     */
    public java.lang.String getUseType() {
      java.lang.Object ref = useType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string useType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUseTypeBytes() {
      java.lang.Object ref = useType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string useType = 2;</code>
     */
    public Builder setUseType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      useType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string useType = 2;</code>
     */
    public Builder clearUseType() {
      
      useType_ = getDefaultInstance().getUseType();
      onChanged();
      return this;
    }
    /**
     * <code>string useType = 2;</code>
     */
    public Builder setUseTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      useType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object messageContent_ = "";
    /**
     * <code>string messageContent = 3;</code>
     */
    public java.lang.String getMessageContent() {
      java.lang.Object ref = messageContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string messageContent = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageContentBytes() {
      java.lang.Object ref = messageContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string messageContent = 3;</code>
     */
    public Builder setMessageContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string messageContent = 3;</code>
     */
    public Builder clearMessageContent() {
      
      messageContent_ = getDefaultInstance().getMessageContent();
      onChanged();
      return this;
    }
    /**
     * <code>string messageContent = 3;</code>
     */
    public Builder setMessageContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageContent_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.rome.common.rpc.message.VerificationCodeReq)
  }

  // @@protoc_insertion_point(class_scope:com.rome.common.rpc.message.VerificationCodeReq)
  private static final com.rome.common.rpc.message.VerificationCodeReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rome.common.rpc.message.VerificationCodeReq();
  }

  public static com.rome.common.rpc.message.VerificationCodeReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerificationCodeReq>
      PARSER = new com.google.protobuf.AbstractParser<VerificationCodeReq>() {
    @java.lang.Override
    public VerificationCodeReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VerificationCodeReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VerificationCodeReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerificationCodeReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rome.common.rpc.message.VerificationCodeReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

